services:
    _defaults:
        public: true
    analytics_service:
         class: rtPiwikBundle\Services\Analytics
    metrics_service:
         class: rtPiwikBundle\Services\MetricsService
         arguments:
            $analytics: '@analytics_service'
    total_metrics:
        class: rtPiwikBundle\Services\TotalMetrics
        arguments:
            $metricsService: '@metrics_service'
    daily_metrics:
        class: rtPiwikBundle\Services\DailyMetrics
        arguments:
            $metricsService: '@metrics_service'
    weekly_metrics:
        class: rtPiwikBundle\Services\WeeklyMetrics
        arguments:
            $metricsService: '@metrics_service'
