services:
    _defaults:
        public: true
    analytics_service:
         class: rtPiwikBundle\Services\Analytics
    metrics_service:
         class: rtPiwikBundle\Services\MetricsService
         arguments:
            $analytics: '@analytics_service'
    common_metrics:
        class: rtPiwikBundle\Services\CommonMetrics
        arguments:
            $metricsService: '@metrics_service'
    total_metrics:
        class: rtPiwikBundle\Services\TotalMetrics
        arguments:
            $metricsService: '@metrics_service'
